spring.application.name=crvg

# Configuracoes de conexao do H2
spring.datasource.url=jdbc:h2:mem:cinemadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web do H2 para conseguir ver as tabelas criadas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracoes do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Exibe os SQLs que o Hibernate esta executando no console da IDE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Login e senha do spring security
spring.security.user.name=admin
spring.security.user.password=admin
