spring.application.name=crvg

# Configurações de conexão do H2
spring.datasource.url=jdbc:h2:mem:cinemadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web do H2 para conseguir ver as tabelas criadas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostra os SQLs que o Hibernate está executando no console da IDE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
